import requests
from bs4 import BeautifulSoup
import pyttsx3
voice=pyttsx3.init()
url = ("https://timesofindia.indiatimes.com/")
page = requests.get(url)
soup=BeautifulSoup(page.content, 'html.parser')
m=soup.find_all("figcaption")

n1=(m[0].get_text())
n2=(m[1].get_text())
n3=(m[2].get_text())
n4=(m[3].get_text())
n5=(m[4].get_text())
n6=(m[5].get_text())
n7=(m[6].get_text())
n8=(m[7].get_text())
n9=(m[8].get_text())
def news():
    print(n1)
    voice.say(n1)
    print(n2)
    voice.say(n2)
    print(n3)
    voice.say(n3)
    print(n4)
    voice.say(n4)
    print(n5)
    voice.say(n5)
    print(n6)
    voice.say(n6)
    print(n7)
    voice.say(n7)
    print(n8)
    voice.say(n8)
    print(n9)
    voice.say(n9)
    voice.runAndWait()